// Real brand/company logos by domain or ticker, with a graceful monogram fallback.
//
// REAL, full-resolution logos for every stock + broker need a free logo.dev
// token: set NEXT_PUBLIC_LOGODEV_TOKEN (1-min signup at logo.dev) and every
// SymbolLogo/BrandLogo upgrades automatically (domain AND ticker lookups).
// Without a token we fall back to gstatic's 128px favicon (best key-less
// option) and then to a clean initials monogram — never a broken image.
//
// We never hand-trace trademarks: logos are fetched from the brand's own
// public domain/ticker for nominative identification (the broker you connect,
// the stock you watch).

// Full NSE ticker->domain map generated by scripts/data/resolve_logos.py
// (logo.dev Brand Search over the backend `instruments` company list).
import GENERATED_DOMAINS from './symbol-domains.json'

const LOGODEV = process.env.NEXT_PUBLIC_LOGODEV_TOKEN

/** Logo by company domain (e.g. "tcs.com", "zerodha.com"). */
export function logoUrl(domain: string | undefined, size = 128): string {
  if (!domain) return ''
  if (LOGODEV) return `https://img.logo.dev/${domain}?token=${LOGODEV}&size=${size}&format=png&retina=true`
  // Free fallback: gstatic favicon proxy (up to 128px, far better than ip3).
  return `https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&size=${Math.min(size, 128)}&url=https://${domain}`
}

/** Logo by stock ticker via logo.dev (token only). Covers names with no domain
 *  in the map; empty string when no token (caller then uses domain/monogram). */
export function tickerLogoUrl(ticker: string | undefined, size = 128): string {
  if (!ticker || !LOGODEV) return ''
  return `https://img.logo.dev/ticker/${encodeURIComponent(ticker)}?token=${LOGODEV}&size=${size}&format=png&retina=true`
}

// Broker domains for the direct-connect set (OAuth: Zerodha / Upstox / Fyers;
// credentials: Angel One / Dhan).
export const BROKER_DOMAIN: Record<string, string> = {
  zerodha: 'zerodha.com',
  upstox: 'upstox.com',
  angelone: 'angelone.in',
  fyers: 'fyers.in',
  dhan: 'dhan.co',
  kotakneo: 'kotaksecurities.com',
  aliceblue: 'aliceblueonline.com',
}

// Curated ticker -> domain for the most-traded NSE names (hand-checked, accurate).
// Merged BELOW with the generated full-universe map; curated wins on conflict.
const CURATED_DOMAIN: Record<string, string> = {
  RELIANCE: 'ril.com', TCS: 'tcs.com', INFY: 'infosys.com', HDFCBANK: 'hdfcbank.com',
  ICICIBANK: 'icicibank.com', SBIN: 'sbi.co.in', HINDUNILVR: 'hul.co.in', ITC: 'itcportal.com',
  BHARTIARTL: 'airtel.in', KOTAKBANK: 'kotak.com', LT: 'larsentoubro.com', AXISBANK: 'axisbank.com',
  ASIANPAINT: 'asianpaints.com', MARUTI: 'marutisuzuki.com', TITAN: 'titan.co.in', SUNPHARMA: 'sunpharma.com',
  WIPRO: 'wipro.com', HCLTECH: 'hcltech.com', ULTRACEMCO: 'ultratechcement.com', NESTLEIND: 'nestle.in',
  BAJFINANCE: 'bajajfinserv.in', BAJAJFINSV: 'bajajfinserv.in', ADANIENT: 'adani.com', ADANIPORTS: 'adaniports.com',
  POWERGRID: 'powergrid.in', NTPC: 'ntpc.co.in', ONGC: 'ongcindia.com', COALINDIA: 'coalindia.in',
  TATAMOTORS: 'tatamotors.com', TATASTEEL: 'tatasteel.com', TATAPOWER: 'tatapower.com', JSWSTEEL: 'jsw.in',
  HINDALCO: 'hindalco.com', GRASIM: 'grasim.com', CIPLA: 'cipla.com', DRREDDY: 'drreddys.com',
  DIVISLAB: 'divislabs.com', BRITANNIA: 'britannia.co.in', DABUR: 'dabur.com', EICHERMOT: 'eichermotors.com',
  HEROMOTOCO: 'heromotocorp.com', BAJAJ_AUTO: 'bajajauto.com', BAJAJAUTO: 'bajajauto.com', M_M: 'mahindra.com',
  TECHM: 'techmahindra.com', INDUSINDBK: 'indusind.com', SBILIFE: 'sbilife.co.in', HDFCLIFE: 'hdfclife.com',
  BPCL: 'bharatpetroleum.in', SHRIRAMFIN: 'shriramfinance.in', APOLLOHOSP: 'apollohospitals.com',
  ZOMATO: 'zomato.com', PAYTM: 'paytm.com', NYKAA: 'nykaa.com', DMART: 'dmartindia.com', PIDILITIND: 'pidilite.com',
  VEDL: 'vedantalimited.com', GAIL: 'gailonline.com', IOC: 'iocl.com', DLF: 'dlf.in', SIEMENS: 'siemens.com',
  // Banks / NBFCs / insurance
  BANKBARODA: 'bankofbaroda.in', PNB: 'pnbindia.in', CANBK: 'canarabank.com', IDFCFIRSTB: 'idfcfirstbank.com',
  FEDERALBNK: 'federalbank.co.in', AUBANK: 'aubank.in', BANDHANBNK: 'bandhanbank.com', CHOLAFIN: 'cholamandalam.com',
  MUTHOOTFIN: 'muthootfinance.com', ICICIPRULI: 'iciciprulife.com', ICICIGI: 'icicilombard.com', HDFCAMC: 'hdfcfund.com',
  SBICARD: 'sbicard.com', PFC: 'pfcindia.com', RECLTD: 'recindia.nic.in', IRFC: 'irfc.co.in', LICI: 'licindia.in',
  JIOFIN: 'jfs.in', BAJAJHLDNG: 'bajajholdings.in',
  // Auto / ancillaries
  TVSMOTOR: 'tvsmotor.com', ASHOKLEY: 'ashokleyland.com', BHARATFORG: 'bharatforge.com', MOTHERSON: 'motherson.com',
  BOSCHLTD: 'bosch.in', MRF: 'mrftyres.com', BALKRISIND: 'bkt-tires.com',
  // Metals / cement / chem / infra
  JINDALSTEL: 'jindalsteelpower.com', SAIL: 'sail.co.in', NMDC: 'nmdc.co.in', NATIONALUM: 'nalcoindia.com',
  APLAPOLLO: 'aplapollo.com', AMBUJACEM: 'ambujacement.com', SHREECEM: 'shreecement.com', ACC: 'acclimited.com',
  PIIND: 'piindustries.com', SRF: 'srf.com', UPL: 'upl-ltd.com', POLYCAB: 'polycab.com',
  // Pharma / healthcare
  TORNTPHARM: 'torrentpharma.com', LUPIN: 'lupin.com', AUROPHARMA: 'aurobindo.com', ALKEM: 'alkemlabs.com',
  ZYDUSLIFE: 'zyduslife.com', GLENMARK: 'glenmarkpharma.com', BIOCON: 'biocon.com', MANKIND: 'mankindpharma.com',
  MAXHEALTH: 'maxhealthcare.in', FORTIS: 'fortishealthcare.com',
  // IT / new-age
  LTIM: 'ltimindtree.com', PERSISTENT: 'persistent.com', COFORGE: 'coforge.com', MPHASIS: 'mphasis.com',
  OFSS: 'oracle.com', NAUKRI: 'infoedge.in', IRCTC: 'irctc.co.in',
  // Consumer / retail / FMCG
  TRENT: 'trentlimited.com', PAGEIND: 'jockey.in', HAVELLS: 'havells.com', VOLTAS: 'voltas.com',
  COLPAL: 'colgate.co.in', GODREJCP: 'godrejcp.com', MARICO: 'marico.com', TATACONSUM: 'tataconsumer.com',
  VBL: 'varunpepsi.com', UBL: 'unitedbreweries.com', INDHOTEL: 'tajhotels.com', INDIGO: 'goindigo.in',
  // Capital goods / energy / telecom / PSU
  ABB: 'abb.com', CGPOWER: 'cgglobal.com', BHEL: 'bhel.com', BEL: 'bel-india.in', HAL: 'hal-india.co.in',
  IGL: 'iglonline.net', PETRONET: 'petronetlng.in', TATACOMM: 'tatacommunications.com', IDEA: 'myvi.in',
  INDUSTOWER: 'industowers.com',
}

// Complete NSE ticker -> domain map: ~720 resolved from the backend company
// list via logo.dev Brand Search, with the curated set above winning on
// conflict (accuracy on the most-traded names). Anything still unmapped falls
// back to logo.dev's ticker lookup, then a clean monogram.
export const SYMBOL_DOMAIN: Record<string, string> = {
  ...(GENERATED_DOMAINS as Record<string, string>),
  ...CURATED_DOMAIN,
}
